### ISSUE TITLE
Translate issue template and maybe code of conduct

### ISSUE THREAD

**Issue by Croos3r** [tarlamaison/tar-le-bot#7]
pls fix @RezaRahemtola or tchetche

**Comment by RezaRahemtola** [comment]
@Croos3r Issue templates are currently in French and code of conduct in English, which one should I translate and in which language ?

**Comment by Croos3r** [comment]
> @Croos3r Issue templates are currently in French and code of conduct in English, which one should I translate and in which language ?

As we're mainly french in the community, I guess we should translate it in French :)
